#YAML
#bowtie_config_file_mitochloro_treatment.yml
---
0_General_system:
  sys:
    - bowtie_path: '/home/davidu/Downloads/bowtie-0.12.5'
    - use_pigz: ~
    - pigz_installation_path: ~
    - use_gzip: check
    - pigz_threads: ~
    - outfile_base_name: FAIRE-3-AT-A-th_ACAGTG_L003_organelle
1_MainArguments:
  main:
    - ebwt: TAIR10_mitochloro
    - m1:
      - FAIRE-3-AT-A-th_ACAGTG_L003_mitochlorounaligned_1/FAIRE-3-AT-A-th_ACAGTG_L003_mitochlorounaligned_1_fastx_artifacts_fastq_quality_filter_quality_trimmer.fastq_head1000
    - m2:
      - FAIRE-3-AT-A-th_ACAGTG_L003_mitochlorounaligned_2/FAIRE-3-AT-A-th_ACAGTG_L003_mitochlorounaligned_2_fastx_artifacts_fastq_quality_filter_quality_trimmer.fastq_head1000
    - r:
      - ~
    - s:
      - ~
    - hit: ~
2_Input:
  flags:
    - q: ~
    - f: ~
    - r: ~
    - c: ~
    - color: ~
    - phred33-quals: ~
    - phred64-quals: ~
    - solexa-quals: ~
    - solexa1.3-quals: ~
    - integer-quals: ~
  values:
    - quals: ~
    - Q1: ~
    - Q2: ~
    - skip: ~
    - qupto: ~
    - trim5: ~
    - trim3: ~
3_Alignment:
  flags:
    - nomaqround: ~
    - fr: ~
    - rf: ~
    - ff: ~
    - nofw: ~
    - norc: ~
    - maxbts: ~
    - tryhard: ~
  values:
    - v: ~
    - seedmms: 2
    - maqerr: ~
    - seedlen: ~
    - minins: ~
    - maxins: ~
    - pairtries: ~
    - chunkmbs: 256
4_Reporting:
  flags:
    - all: ~
    - best: ~
    - strata: ~
  values:
    - k: ~
    - m: ~
    - M: ~
5_Output:
  flags:
    - time: check
    - quiet: ~
    - refout: ~
    - refidx: ~
    - fullref: ~
  values:
    - offbase: ~
    - al: ~
    - un: FAIRE-3-AT-A-th_ACAGTG_L003_organelle_unaligned
    - max: ~
    - suppress: ~
6_Colorspace:
  flags:
    - col-cseq: ~
    - col-cqual: ~
    - col-keepends: ~
  values:
    - snpphred: ~
    - snpfrac: ~
7_SAM:
  flags:
    - sam: check
    - sam-nohead: ~
    - sam-nosq: ~
  values:
    - mapq: ~
    - sam-RG: ~
8_Performance:
  flags:
    - mm: ~
    - shmem: ~
  values:
    - offrate: ~
    - threads: 2
