#YAML
#bowtie_build_config_file.yml
---
1_main_arguments:
  values:
    - bowtie-path: /home/davidu/Downloads/bowtie-0.12.5
    - reference_in: Genomes/TAIR10/TAIR10_nuclear.fasta
    - ebwt_base: TAIR10_nuclear

2_construct_advanced_options:
  flags:
    - noauto_index: ~
    - packed: ~
    - no_rf: ~
    - just_ref: ~ 
    
    - ntoa: ~
    
  values:
    - bmax: ~
    - bmaxdivn: ~ 
    - no_dc: ~
    
    - off_rate: ~
    - ftabchars: ~
    
    - seed: ~
    - cutoff: ~
3_other_arguments: 
  flags:
    - color_index: ~
