#YAML try 
#fast-toolkit_config_file.yml
#output is set to the script running location
fastx_path: '/home/davidu/Downloads/fastx-toolkit/bin' 
in_file: 'sample_files_ligth/FAIRE-WT-A-th_GCCAAT_L004_mitochlorounaligned_1.fastq_head1000'
stats_graphs:
  perform: check
  order: 1,13
clipper: 
  perform: ~
  order: 2
  adapter_seq: ~
  discard_length: ~
  keep_adapt_lenplus: ~
  discard_non_clip: check
  discard_clip: ~
  adapter_only: ~
  keep_n_sec: check
  histogram: ~ #not supported
  save_previous_file: ~
trimmer:
  perform: ~
  order: 3 
  first_base: 1
  last_base: 50
  save_previous_file: check
renamer:
  perform: ~
  order: 4
  rename_type: ~ 
  save_previous_file: ~
collapser:
  perform: ~
  order: 5
  save_previous_file: ~
artifacts_filter:
  perform: check
  order: 6
  save_previous_file: ~
quality_filter:
  perform: check
  order: 7
  minimum_quality: 20
  minimum_percentage: 80
  save_previous_file: ~
quality_trimmer:
  perform: check
  order: 8
  quality_thr: 20
  min_length: 30
  save_previous_file: ~
quality_converter:
  perform: ~
  order: 9
  scores: ASCII #ASCII or numeric
  save_previous_file: ~
uncollapser:
  perform: ~
  order: 10
  tab_format : check
  tab_col : ~
  save_previous_file: ~
masker:
  perform: ~
  order: 11
  quality_thr: 20
  save_previous_file: ~
reverse_complement:
  perform: ~
  order: 12
  save_previous_file: ~








